// The five category pages: one section of the work each, every item in it.
//
// They used to be five hand-written files that had drifted into three header
// treatments and three card systems. They are generated now, from
// src/categories/<slug>.json through src/render/category.mjs, which is what
// makes "one design language" a property of the build rather than a tidy-up
// somebody has to repeat. The contract lives here.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadLibrary, loadCategories, ROOT } from "../src/lib/load.mjs";
import { validateCategory } from "../src/validate.mjs";
import { renderAll } from "../src/build.mjs";

const lib = loadLibrary();
const categories = loadCategories();
const read = (name) => readFileSync(join(ROOT, name), "utf8");
const assetExists = (path) => existsSync(join(ROOT, path));
const cards = (html) => [...html.matchAll(/<article class="cat-card"[\s\S]*?<\/article>/g)].map((m) => m[0]);

test("all five sections of the work are generated, none by hand", () => {
  assert.deepEqual(
    categories.map((c) => c.output).sort(),
    ["ai-products.html", "ai-tools.html", "brand.html", "interactive.html", "work.html"],
  );
  for (const c of categories) {
    assert.match(read(c.output), /GENERATED by src\/build\.mjs from src\/categories\//,
      `${c.output}: must carry the generated banner, so nobody edits it by hand`);
  }
});

test("the committed pages are exactly what the build produces", () => {
  const pages = renderAll({ lib, categories });
  for (const c of categories) {
    assert.equal(read(c.output), pages.get(c.output),
      `${c.output} is stale — run: node src/build.mjs`);
  }
});

test("every category validates: real evidence, no duplicates, links that exist", () => {
  for (const c of categories) {
    assert.deepEqual(validateCategory(c, lib, { assetExists }), [], `category:${c.slug}`);
  }
});

test("each page carries its own section's cards, in the configured order", () => {
  for (const c of categories) {
    const html = read(c.output);
    const expected = c.groups.flatMap((g) => g.items);
    const rendered = cards(html).map((card) => {
      const m = card.match(/<h3 class="cat-card-title">([\s\S]*?)<\/h3>/);
      return m[1].replace(/<[^>]+>/g, "").trim();
    });
    assert.equal(rendered.length, expected.length, `${c.output}: card count`);
    const names = expected.map((id) => {
      const item = lib.evidence.get(id);
      return (item.shortTitle ?? item.title);
    });
    for (const [i, name] of names.entries()) {
      assert.ok(rendered[i].startsWith(name), `${c.output}: card ${i + 1} should be ${name}, got "${rendered[i]}"`);
    }
  }
});

test("one h1 per page, and the nav marks the section you are standing in", () => {
  for (const c of categories) {
    const html = read(c.output);
    assert.equal([...html.matchAll(/<h1\b/gi)].length, 1, `${c.output}: exactly one h1`);
    const active = [...html.matchAll(/<a href="([^"]+)" class="is-active" aria-current="page">/g)].map((m) => m[1]);
    assert.deepEqual(active, [c.output], `${c.output}: its own nav item, and only its own`);
  }
});

test("two columns, one card shape, one thumbnail ratio", () => {
  // Three columns puts a card at 279px, where Japanese wraps every 13
  // characters — the reason the old category pages were hard to read.
  const css = read("src/render/lens.css");
  assert.match(css, /\.cat-grid \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.cat-card-media \{[^}]*aspect-ratio: 3 \/ 2/);
  for (const c of categories) {
    const html = read(c.output);
    assert.equal(/class="work-card"/.test(html), false, `${c.output}: the old card system must be gone`);
    assert.equal(/class="idx-tile"/.test(html), false, `${c.output}: the old index system must be gone`);
    for (const card of cards(html)) {
      assert.match(card, /<div class="cat-card-media">/, `${c.output}: every card leads with its media box`);
      assert.ok(/<img /.test(card) || /class="card-art /.test(card),
        `${c.output}: a media box must hold an image or the CSS artwork standing in for one`);
    }
  }
});

test("a card says one thing, not a paragraph", () => {
  // The complaint that started this: the card copy read like case-study
  // abstracts, because it was the case-study abstract.
  for (const c of categories) {
    for (const id of c.groups.flatMap((g) => g.items)) {
      const line = lib.evidence.get(id).cardLine;
      assert.ok(line?.en && line?.jp, `${id}: needs a cardLine in both languages`);
      assert.ok(line.en.length <= 120, `${id}: card line is ${line.en.length} chars — keep it under 120`);
      assert.equal(line.en.trim().split(". ").length <= 2, true, `${id}: one sentence, two at the outside`);
    }
  }
});

test("a card that opens a project page opens the project page, not the repo", () => {
  // A card whose destination is a case study on this site must go there. The
  // repo link belongs on the project page, where it can be explained.
  for (const c of categories) {
    const html = read(c.output);
    for (const id of c.groups.flatMap((g) => g.items)) {
      const item = lib.evidence.get(id);
      if (!item.links?.caseStudy) continue;
      if (item.playable && item.links.live) continue;
      const card = cards(html).find((k) => k.includes(`href="${item.links.caseStudy}"`));
      assert.ok(card, `${c.output}: ${id} should link to ${item.links.caseStudy}`);
      assert.equal(/data-external="true"/.test(card), false, `${c.output}: ${id} is an internal page`);
    }
  }
});

test("every destination a card offers actually resolves", () => {
  for (const c of categories) {
    const html = read(c.output);
    for (const m of html.matchAll(/<a class="cat-card-cta" href="([^"]+)"/g)) {
      const url = m[1];
      if (/^https?:/.test(url)) continue;
      assert.ok(assetExists(url.split("#")[0]), `${c.output}: "${url}" is not on disk`);
    }
  }
});
