/* ============================================================
   Amazon Shopping for Fire TV — Product Catalog (POC)
   Data grounded in saved amazon.com pages (FromAmazon/), July 2026.
   Images served from Amazon's public CDN (m.media-amazon.com).
   ============================================================ */

const CDN = (id, size) => `https://m.media-amazon.com/images/I/${id}._AC_SL${size || 600}_.jpg`;

const CATALOG = [
  {
    id: 'optimum',
    asin: 'B000QSNYGI',
    brand: 'Optimum Nutrition',
    title: 'Optimum Nutrition Gold Standard 100% Whey Protein Powder, Double Rich Chocolate, 24g Protein, 2 Pound',
    short: 'Gold Standard 100% Whey',
    img: '71Lw7FkgniL',
    gallery: ['71Lw7FkgniL', '81VckjXWctL', '81B6R1fJFuL', '812U5xh1T1L', '81omYbGE6gL', '81pkJH9JzfL'],
    price: 38.99, listPrice: 45.99, unit: '$1.22/Ounce',
    rating: 4.7, ratings: 241873, bought: '10K+ bought in past month',
    badge: 'Best Seller', prime: true, sns: 10,
    protein: '24g', servings: 29, type: 'whey',
    flavors: ['Double Rich Chocolate', 'Vanilla Ice Cream', 'Extreme Milk Chocolate', 'Cookies & Cream'],
    sizes: [{ label: '2 LB (29 servings)', price: 38.99 }, { label: '5 LB (71 servings)', price: 79.99 }],
    tags: ['chocolate', 'whey', 'isolate-blend', 'gluten-free'],
    bullets: [
      '24g of whey protein per serving with whey protein isolate as the primary ingredient',
      '5.5g of naturally occurring BCAAs and 11g of naturally occurring EAAs per serving',
      'Over 20 tempting flavors — the world\'s best-selling whey protein powder',
      'Banned substance tested — Informed Choice certified for sport',
      'Anytime formula: great first thing in the morning or after workouts',
    ],
    customersSay: 'Customers find this protein powder mixes easily and has a great chocolate taste that isn\'t too sweet. They appreciate the quality protein content and consider it good value, with many buying it for years. Some customers note the packaging scoop is buried in the powder.',
    aspects: { positive: ['Taste', 'Mixability', 'Protein quality', 'Value'], negative: ['Scoop placement'] },
    reviews: [
      { stars: 5, title: 'The gold standard for a reason', author: 'Mike R.', date: 'June 28, 2026', text: 'Been using this for 8 years. Mixes perfectly with just a shaker, tastes like chocolate milk with water, and my recovery is noticeably better. Double Rich Chocolate is the safest flavor pick on Amazon.' },
      { stars: 5, title: 'Consistent quality every order', author: 'Sarah T.', date: 'June 15, 2026', text: 'I subscribe & save and it shows up every month. No clumps, no weird aftertaste, blends great with banana and peanut butter.' },
      { stars: 4, title: 'Great protein, find the scoop!', author: 'Daniel K.', date: 'May 30, 2026', text: 'Only complaint is the scoop is always buried at the bottom. Otherwise, the best-mixing whey I have tried at this price.' },
    ],
    rufus: [
      { q: 'Is this good for muscle building?', a: 'Yes — each serving delivers 24g of fast-digesting whey with 5.5g BCAAs including leucine, which triggers muscle protein synthesis. It\'s the most-reviewed whey on Amazon and is banned-substance tested for athletes.' },
      { q: 'How does it taste with water?', a: 'Double Rich Chocolate is known for tasting good with just water — customers describe it like light chocolate milk. It\'s less sweet than most competitors.' },
      { q: 'Whey concentrate or isolate?', a: 'It\'s a blend with whey protein isolate listed first, plus concentrate and peptides. About 79% protein by weight — a strong mid-point between pure isolates and budget concentrates.' },
    ],
  },
  {
    id: 'jocko',
    asin: 'B0CH1T1ZPM',
    brand: 'Jocko Fuel',
    title: 'Jocko Fuel Mölk Whey Protein Powder, Vanilla Milkshake — 22g Protein, Digestive Enzymes + Probiotic Blend, No Sugar Added, 28 Servings',
    short: 'Jocko Mölk Whey Protein',
    img: '71laNd2B+IL',
    gallery: ['71laNd2B+IL', '818iHR56-bL', '811Nw8wC6sL', '61juqzxMLHL', '61udgPTs6oL', '61vZbruJWNL'],
    price: 44.97, listPrice: null, unit: '$1.61/Ounce',
    rating: 4.6, ratings: 21446, bought: '5K+ bought in past month',
    badge: "Amazon's Choice", prime: true, sns: 15,
    protein: '22g', servings: 28, type: 'whey',
    flavors: ['Vanilla Milkshake', 'Chocolate Peanut Butter', 'Mint Chocolate', 'Banana Cream'],
    sizes: [{ label: '28 Servings', price: 44.97 }],
    tags: ['vanilla', 'whey', 'probiotics', 'no-sugar-added'],
    bullets: [
      '22g of protein per serving from a time-released blend of whey and casein',
      'Digestive enzyme + probiotic blend for easier digestion',
      'No sugar added — naturally sweetened with monk fruit',
      'Essential amino acids + electrolyte minerals for recovery',
      'Made in the USA in a GMP-certified facility',
    ],
    customersSay: 'Customers praise the vanilla milkshake flavor as one of the best-tasting proteins with no artificial aftertaste. They value the added probiotics for easy digestion. A few customers find it slightly foamy right after shaking.',
    aspects: { positive: ['Flavor', 'Digestibility', 'Clean ingredients'], negative: ['Foam after shaking'] },
    reviews: [
      { stars: 5, title: 'GOOD.', author: 'Alex P.', date: 'July 2, 2026', text: 'Discipline equals freedom, and this shake equals dessert. Vanilla Milkshake with cold milk is genuinely the best protein flavor I\'ve had. Zero stomach issues thanks to the enzymes.' },
      { stars: 5, title: 'Finally one that doesn\'t hurt my stomach', author: 'Jennifer M.', date: 'June 20, 2026', text: 'The probiotic blend makes a real difference. I switched from a big-name brand and the bloating is gone completely.' },
      { stars: 4, title: 'Tastes great, a little foamy', author: 'Chris B.', date: 'June 5, 2026', text: 'Let it sit a minute after shaking and it\'s perfect. Monk fruit sweetener is way better than sucralose.' },
    ],
    rufus: [
      { q: 'Does it have artificial sweeteners?', a: 'No — Jocko Mölk is sweetened with monk fruit, with no added sugar and no sucralose or aspartame. That\'s a key reason customers pick it over mainstream brands.' },
      { q: 'Is it easy to digest?', a: 'Yes — it includes a digestive enzyme and probiotic blend, and reviewers frequently mention less bloating compared to other whey proteins.' },
      { q: 'When should I take it?', a: 'The whey + casein time-released blend works after workouts and also before bed for overnight recovery.' },
    ],
  },
  {
    id: 'levels',
    asin: 'B071JG5QYT',
    brand: 'Levels',
    title: 'Levels Grass Fed 100% Whey Protein, No Artificials, Vanilla Bean, 24g Protein, 2LB',
    short: 'Levels Grass Fed Whey',
    img: '61v1-ocOzXL',
    gallery: ['61v1-ocOzXL', '71a5nC6VmkL', '81hNBGx1DwL', '717p71yx7kL', '715e-fy0keL', '81MWqdNPNCL'],
    price: 39.95, listPrice: null, unit: '$1.25/Ounce',
    rating: 4.5, ratings: 41387, bought: '3K+ bought in past month',
    badge: null, prime: true, sns: 10,
    protein: '24g', servings: 27, type: 'whey',
    flavors: ['Vanilla Bean', 'Double Chocolate', 'Unflavored', 'Chocolate Mocha'],
    sizes: [{ label: '2 LB', price: 39.95 }, { label: '5 LB', price: 74.99 }],
    tags: ['vanilla', 'whey', 'grass-fed', 'hormone-free'],
    bullets: [
      '24g of protein and 5.4g of BCAAs per scoop from grass-fed cows',
      'No artificial ingredients — zero junk, no fillers, no added sugar',
      'Made with hormone-free dairy, certified clean',
      'Cold-processed, undenatured whey concentrate',
      'Mixes smooth — no gums or thickeners',
    ],
    customersSay: 'Customers describe this as a clean protein with a mild, natural vanilla flavor and short ingredient list. They like that it uses real vanilla bean. Some note it is sweetened lightly, which they prefer, while others want a stronger flavor.',
    aspects: { positive: ['Clean ingredients', 'Natural flavor', 'Mixability'], negative: ['Mild sweetness'] },
    reviews: [
      { stars: 5, title: 'Cleanest whey on Amazon', author: 'Rachel W.', date: 'June 25, 2026', text: 'Five ingredients. That\'s it. Tastes like lightly sweet vanilla milk and my macros love it.' },
      { stars: 5, title: 'Grass-fed quality you can taste', author: 'Tom H.', date: 'June 10, 2026', text: 'Smooth blend, no chalkiness, and the vanilla bean specks are a nice touch of authenticity.' },
      { stars: 4, title: 'Great, if you like subtle', author: 'Priya S.', date: 'May 22, 2026', text: 'If you\'re coming from candy-sweet proteins this will taste plain at first. Give it a week — now everything else is too sweet for me.' },
    ],
    rufus: [
      { q: 'Is this actually grass-fed?', a: 'Yes — Levels sources whey exclusively from grass-fed, hormone-free (rBGH/rBST-free) cows, and it\'s cold-processed to keep the whey undenatured.' },
      { q: 'What\'s in the ingredient list?', a: 'Just five ingredients: grass-fed whey concentrate, natural flavors, real vanilla bean, sea salt, and stevia. No gums, fillers, or artificial sweeteners.' },
      { q: 'Good for smoothies?', a: 'Very — with no thickeners it blends clean into smoothies without turning gummy, which reviewers frequently call out.' },
    ],
  },
  {
    id: 'ascent',
    asin: 'B01N7VLTW3',
    brand: 'Ascent',
    title: 'Ascent 100% Whey Protein Powder — Post Workout Whey Isolate, Zero Artificial Flavors & Sweeteners, 5.5g BCAA, Vanilla Bean, 2 lb',
    short: 'Ascent Native Fuel Whey',
    img: '41-N7LxroFL', imgSize: 'SR300,300',
    gallery: ['41-N7LxroFL'],
    price: 48.99, listPrice: 56.99, unit: '$1.53/Ounce',
    rating: 4.6, ratings: 18234, bought: '2K+ bought in past month',
    badge: null, prime: true, sns: 10,
    protein: '25g', servings: 27, type: 'isolate',
    flavors: ['Vanilla Bean', 'Chocolate', 'Chocolate Peanut Butter', 'Unflavored'],
    sizes: [{ label: '2 LB', price: 48.99 }, { label: '4 LB', price: 86.99 }],
    tags: ['vanilla', 'whey', 'isolate', 'keto', 'gluten-free'],
    bullets: [
      '25g of pure native whey isolate per scoop for rapid post-workout recovery',
      'Zero artificial flavors or sweeteners — lightly sweetened with stevia leaf',
      '0g added sugar, low-carb: fits keto lifestyles',
      'Naturally higher in leucine (2.6g) for muscle protein synthesis',
      'Gluten-free; mixes silky smooth with just cold water',
    ],
    customersSay: 'According to customers, Ascent tastes great and mixes easily, with a clean vanilla flavor from real ingredients. They highlight fast digestion after workouts. Some feel the price is higher than comparable isolates.',
    aspects: { positive: ['Clean formula', 'Mixability', 'Recovery'], negative: ['Price'] },
    reviews: [
      { stars: 5, title: 'Official protein of hard workouts', author: 'Marcus L.', date: 'June 30, 2026', text: 'Native whey isolate digests instantly. No bloat mid-workout the next morning. Worth the premium.' },
      { stars: 5, title: 'Silky smooth with water only', author: 'Emily C.', date: 'June 12, 2026', text: 'Dissolves with three shakes. Vanilla bean tastes like melted ice cream, not chemicals.' },
      { stars: 4, title: 'Excellent but pricey', author: 'Jordan F.', date: 'May 18, 2026', text: 'Best-in-class quality. I wait for Subscribe & Save plus coupons to stack before ordering.' },
    ],
    rufus: [
      { q: 'Why is native whey better?', a: 'Native whey is filtered directly from milk instead of being a cheese byproduct — it\'s less processed and naturally about 13% higher in leucine, the key amino acid for muscle building.' },
      { q: 'Is it keto friendly?', a: 'Yes — with 0g added sugar and low carbs per scoop, Ascent markets this as keto-friendly, and it\'s sweetened only with stevia leaf extract.' },
      { q: 'How does it compare to Gold Standard?', a: 'Ascent is a pure isolate with a cleaner label (no artificial sweeteners) at a higher price; Gold Standard is an isolate blend with more flavors and a lower cost per serving. For fastest recovery, Ascent; for value, Gold Standard.' },
    ],
  },
  {
    id: 'orgain',
    asin: 'B00J074W7Q',
    brand: 'Orgain',
    title: 'Orgain Organic Vegan Protein Powder, Vanilla Bean — 21g Plant Protein, 6g Prebiotic Fiber, No Lactose, No Added Sugar, Non-GMO, 2.03 lb',
    short: 'Orgain Organic Plant Protein',
    img: '41YPR-HA3mL',
    gallery: ['41YPR-HA3mL'],
    price: 29.59, listPrice: 34.99, unit: '$0.91/Ounce',
    rating: 4.5, ratings: 94213, bought: '8K+ bought in past month',
    badge: 'Overall Pick', prime: true, sns: 15,
    protein: '21g', servings: 20, type: 'plant',
    flavors: ['Vanilla Bean', 'Creamy Chocolate Fudge', 'Peanut Butter', 'Strawberries & Cream'],
    sizes: [{ label: '2.03 LB', price: 29.59 }],
    tags: ['vanilla', 'plant', 'vegan', 'organic', 'dairy-free', 'gluten-free'],
    bullets: [
      '21g of organic plant-based protein from pea, brown rice and chia seeds',
      '6g of organic prebiotic fiber per serving for digestive health',
      'No lactose ingredients, no added sugar, non-GMO',
      'USDA Organic, vegan, gluten free, soy free, kosher',
      'Great for shakes, smoothies, and baking',
    ],
    customersSay: 'Customers appreciate this plant protein\'s smooth texture compared to other vegan powders and its mild vanilla taste. Many buy it for lactose intolerance and note it doesn\'t upset their stomach. Some mention a slightly earthy pea-protein finish.',
    aspects: { positive: ['Smooth for a vegan protein', 'Gentle on stomach', 'Organic'], negative: ['Earthy aftertaste'] },
    reviews: [
      { stars: 5, title: 'Best plant protein I\'ve found', author: 'Nina G.', date: 'June 27, 2026', text: 'I\'ve tried six vegan proteins and this is the only one that isn\'t gritty. Blends beautifully with oat milk and a banana.' },
      { stars: 5, title: 'Stomach-friendly at last', author: 'David O.', date: 'June 8, 2026', text: 'Lactose intolerant and this changed my post-gym routine. The prebiotic fiber is a bonus.' },
      { stars: 4, title: 'Good, slightly earthy', author: 'Kate M.', date: 'May 25, 2026', text: 'You can tell it\'s pea protein at the end of the sip. Cinnamon fixes it completely.' },
    ],
    rufus: [
      { q: 'Is this good for lactose intolerance?', a: 'Yes — it contains no lactose ingredients and is fully vegan. Reviewers with dairy sensitivity frequently say it\'s gentle on the stomach.' },
      { q: 'Complete protein?', a: 'The pea + brown rice + chia blend provides all nine essential amino acids, making it a complete plant protein with 21g per serving.' },
      { q: 'Does it work for baking?', a: 'Yes — Orgain is popular for protein pancakes and muffins; the fiber content helps baked goods stay moist.' },
    ],
  },
  {
    id: 'musclemilk',
    asin: 'B0B5L5T76W',
    brand: 'Muscle Milk',
    title: 'Muscle Milk Genuine Protein Powder, Vanilla Crème — 32g Protein, NSF Certified for Sport, 1.93 lb',
    short: 'Muscle Milk Genuine',
    img: '41tF7Hnx8GL',
    gallery: ['41tF7Hnx8GL'],
    price: 23.18, listPrice: 27.99, unit: '$0.75/Ounce',
    rating: 4.6, ratings: 33517, bought: '4K+ bought in past month',
    badge: null, prime: true, sns: 10,
    protein: '32g', servings: 12, type: 'whey',
    flavors: ['Vanilla Crème', 'Chocolate', 'Cookies N Crème', 'Strawberries N Crème'],
    sizes: [{ label: '1.93 LB (12 servings)', price: 23.18 }, { label: '5 LB (32 servings)', price: 54.99 }],
    tags: ['vanilla', 'whey', 'casein-blend', 'nsf-certified'],
    bullets: [
      '32g of protein per 2-scoop serving to help fuel workout recovery',
      'Blend of fast- and slow-release proteins (whey + casein)',
      'NSF Certified for Sport — trusted by professional athletes',
      'With calcium and vitamins A, C & D; 2g sugar',
      'Mix with water or milk, or blend into smoothies',
    ],
    customersSay: 'Customers like the rich, milkshake-style taste and the high 32g protein per serving. Many use it as a meal supplement. Some note servings are two scoops, so the container finishes faster than expected.',
    aspects: { positive: ['Taste', 'Protein per serving', 'Trusted certification'], negative: ['Servings per tub'] },
    reviews: [
      { stars: 5, title: 'Tastes like an actual milkshake', author: 'Greg N.', date: 'June 22, 2026', text: 'Vanilla Crème with cold milk is dessert-level. 32 grams per serving keeps me full for hours.' },
      { stars: 4, title: 'Great macro profile', author: 'Alicia D.', date: 'June 3, 2026', text: 'Solid blend of fast and slow proteins. Just be aware a serving is two scoops.' },
    ],
    rufus: [
      { q: 'Is this NSF certified?', a: 'Yes — Muscle Milk Genuine is NSF Certified for Sport, meaning it\'s independently tested for banned substances. That\'s why it\'s popular with competitive athletes.' },
      { q: 'How much protein per serving?', a: 'A full two-scoop serving delivers 32g of protein — among the highest here — with only 2g of sugar.' },
    ],
  },
  {
    id: 'naked',
    asin: 'B00XIKPUK4',
    brand: 'Naked Nutrition',
    title: 'NAKED Whey 100% Grass Fed Whey Protein Powder — Only 1 Ingredient, Unflavored, Undenatured, No GMOs, 2 lb',
    short: 'Naked Whey — 1 Ingredient',
    img: '31T6eTg13PL',
    gallery: ['31T6eTg13PL'],
    price: 44.99, listPrice: null, unit: '$1.41/Ounce',
    rating: 4.5, ratings: 21284, bought: '1K+ bought in past month',
    badge: null, prime: true, sns: 5,
    protein: '25g', servings: 30, type: 'whey',
    flavors: ['Unflavored', 'Vanilla', 'Chocolate'],
    sizes: [{ label: '2 LB', price: 44.99 }, { label: '5 LB', price: 89.99 }],
    tags: ['whey', 'grass-fed', 'unflavored', 'gluten-free', 'soy-free'],
    bullets: [
      'One ingredient only: whey from grass-fed California cows',
      'Undenatured, cold-processed — no bleaching, no additives',
      '25g protein and 5.9g BCAAs per serving',
      'Gluten free, soy free, no GMOs, no preservatives or sweeteners',
      'Unflavored: disappears into smoothies, oats, and baking',
    ],
    customersSay: 'Customers value the single-ingredient label and buy it to avoid sweeteners entirely. It blends neutrally into any recipe. Reviewers note that as a pure unflavored whey it tastes plain with just water — by design.',
    aspects: { positive: ['Single ingredient', 'No sweeteners', 'Versatile'], negative: ['Plain with water'] },
    reviews: [
      { stars: 5, title: 'Exactly one ingredient. Perfect.', author: 'Hannah B.', date: 'June 18, 2026', text: 'Reading protein labels is exhausting — this one takes 2 seconds. Goes in my morning smoothie unnoticed.' },
      { stars: 4, title: 'Clean but bring your own flavor', author: 'Victor S.', date: 'May 29, 2026', text: 'It\'s unflavored and truly tastes like nothing much. Blend with fruit or cocoa and it\'s ideal.' },
    ],
    rufus: [
      { q: 'What does unflavored taste like?', a: 'Nearly neutral — slightly milky. Customers use it in smoothies, oatmeal and baking where it disappears. If you want a ready-to-drink shake flavor, pick Vanilla or Chocolate instead.' },
      { q: 'Why only one ingredient?', a: 'Naked Whey contains just grass-fed whey concentrate — no sweeteners, emulsifiers or flavorings. It\'s the cleanest label in this list.' },
    ],
  },
  {
    id: 'bulksupplements',
    asin: 'B0128RSQLC',
    brand: 'BulkSupplements',
    title: 'BulkSupplements Grass Fed Whey Protein Concentrate — Unflavored, Gluten Free, 30g per Serving, 2.2 lb',
    short: 'BulkSupplements Grass Fed Whey',
    img: '41ySKDJ5mdL',
    gallery: ['41ySKDJ5mdL'],
    price: 37.97, listPrice: null, unit: '$1.08/Ounce',
    rating: 4.6, ratings: 9142, bought: '900+ bought in past month',
    badge: null, prime: true, sns: 10,
    protein: '30g', servings: 33, type: 'whey',
    flavors: ['Unflavored'],
    sizes: [{ label: '1 KG (2.2 LB)', price: 37.97 }, { label: '5 KG bag', price: 154.96 }],
    tags: ['whey', 'grass-fed', 'unflavored', 'gluten-free', 'value'],
    bullets: [
      '30g of protein per serving from grass-fed whey concentrate',
      'Unflavored and unsweetened — nothing artificial',
      'Lab-tested for purity; manufactured in a cGMP facility',
      'Resealable bulk pouch — lowest cost per gram of protein here',
      'Gluten free, no fillers',
    ],
    customersSay: 'Customers buy this for value: the most protein per dollar in its class. They confirm it mixes reasonably well for a concentrate and appreciate the lab testing. The kraft pouch is less convenient than a tub for scooping.',
    aspects: { positive: ['Value', 'Purity testing', 'High protein'], negative: ['Pouch packaging'] },
    reviews: [
      { stars: 5, title: 'Best protein-per-dollar on Amazon', author: 'Steve K.', date: 'June 9, 2026', text: 'Did the math across 15 products: this wins. Mixes fine in a blender bottle with 30 seconds of shaking.' },
      { stars: 4, title: 'Great value, get a scoop', author: 'Renee L.', date: 'May 16, 2026', text: 'No scoop included — I use a kitchen scale. Otherwise flawless for the price.' },
    ],
    rufus: [
      { q: 'Is this the best value?', a: 'At about $1.15 per 30g serving of protein, yes — it\'s the lowest cost per gram of protein in these results, especially with Subscribe & Save.' },
      { q: 'Does it come with a scoop?', a: 'Reviewers report no scoop in the pouch — most measure with a kitchen scale (about 39g per serving).' },
    ],
  },
  {
    id: 'ascent-casein',
    asin: 'B01NCZACGE',
    brand: 'Ascent',
    title: 'Ascent Micellar Casein Protein Powder — 25g Casein, Zero Artificial Flavors & Sweeteners, Vanilla Bean, 2 lb',
    short: 'Ascent Micellar Casein',
    img: '415d+ZkN47L',
    gallery: ['415d+ZkN47L'],
    price: 44.99, listPrice: null, unit: '$1.41/Ounce',
    rating: 4.6, ratings: 3208, bought: '500+ bought in past month',
    badge: null, prime: true, sns: 10,
    protein: '25g', servings: 26, type: 'casein',
    flavors: ['Vanilla Bean', 'Chocolate'],
    sizes: [{ label: '2 LB', price: 44.99 }],
    tags: ['vanilla', 'casein', 'slow-release', 'gluten-free', 'nighttime'],
    bullets: [
      '25g of slow-digesting micellar casein per serving',
      'Feeds muscles for hours — ideal before bed',
      'Zero artificial flavors or sweeteners; 4.9g BCAAs',
      'Gluten free, no added sugar',
      'Makes thick, pudding-like shakes when blended with less water',
    ],
    customersSay: 'Customers use this as a nighttime protein and like the clean label. Many make it into a pudding texture. Being casein, it mixes thicker than whey — reviewers suggest extra liquid or a blender.',
    aspects: { positive: ['Overnight recovery', 'Clean label', 'Pudding texture'], negative: ['Mixes thick'] },
    reviews: [
      { stars: 5, title: 'The bedtime routine upgrade', author: 'Omar J.', date: 'June 14, 2026', text: 'Casein before bed changed my recovery. Mix it thick like pudding with berries — incredible.' },
      { stars: 4, title: 'Quality casein, needs a blender', author: 'Lily P.', date: 'May 21, 2026', text: 'Shaker alone leaves it thick and clumpy. Blender fixes everything. Taste is clean vanilla.' },
    ],
    rufus: [
      { q: 'Whey or casein — which do I need?', a: 'Whey digests fast (post-workout); casein digests slowly over 6-8 hours, making it ideal before bed. Many athletes use both — whey after training, casein at night.' },
      { q: 'Can I make pudding with it?', a: 'Yes — that\'s a favorite use. Mix with about half the usual liquid and refrigerate 10 minutes for a high-protein pudding.' },
    ],
  },
  {
    id: 'orgain-superfoods',
    asin: 'B07PXNNFGT',
    brand: 'Orgain',
    title: 'Orgain Organic Vegan Protein + 50 Superfoods Powder, Vanilla Bean — 21g Plant Protein, 8g Fiber, 2.02 lb',
    short: 'Orgain Protein + Superfoods',
    img: '41uUNFyV3eL',
    gallery: ['41uUNFyV3eL'],
    price: 34.15, listPrice: 39.99, unit: '$1.06/Ounce',
    rating: 4.5, ratings: 18442, bought: '2K+ bought in past month',
    badge: null, prime: true, sns: 15,
    protein: '21g', servings: 20, type: 'plant',
    flavors: ['Vanilla Bean', 'Creamy Chocolate Fudge'],
    sizes: [{ label: '2.02 LB', price: 34.15 }],
    tags: ['vanilla', 'plant', 'vegan', 'organic', 'superfoods', 'gluten-free'],
    bullets: [
      '21g of organic plant protein plus 50 organic superfoods per scoop',
      'Includes kale, chia, beets, turmeric, and berries blend',
      '8g of organic prebiotic fiber; no added sugar',
      'USDA Organic, vegan, gluten free, non-GMO',
      'A protein shake and greens powder in one',
    ],
    customersSay: 'Customers like combining their protein and greens into one scoop, saving money over buying both. The taste is mildly sweet with an earthy note from the greens. Some prefer blending it with fruit to mask the superfood flavor.',
    aspects: { positive: ['2-in-1 convenience', 'Organic', 'Fiber'], negative: ['Earthy notes'] },
    reviews: [
      { stars: 5, title: 'Replaced two products with one', author: 'Maya R.', date: 'June 19, 2026', text: 'I was buying greens powder AND protein. This does both jobs for less, and blends smooth with banana.' },
      { stars: 4, title: 'Healthy taste, in a good way', author: 'Ben C.', date: 'June 1, 2026', text: 'You can slightly taste the veggies. With frozen berries it becomes my favorite breakfast.' },
    ],
    rufus: [
      { q: 'What superfoods are included?', a: 'The blend spans 50 organic superfoods — greens like kale and spirulina, roots like beets and turmeric, plus berries, chia and flax — alongside 21g of pea-based protein.' },
      { q: 'Is it a meal replacement?', a: 'It\'s closer to a nutrition boost than a full meal — about 170 calories per scoop. Blend with fruit, oats and nut butter for a complete meal shake.' },
    ],
  },
];

/* --- Fallback visual identities for products without CDN images --- */
const BRAND_COLORS = {
  'Optimum Nutrition': ['#1a1a1a', '#c8a951'],
  'Jocko Fuel': ['#0d0d0d', '#e63b2e'],
  Levels: ['#f5efe0', '#2f2a24'],
  Ascent: ['#14213d', '#fca311'],
  Orgain: ['#4a7729', '#f2efe9'],
  Dymatize: ['#0b1f3a', '#e2231a'],
  'Premier Protein': ['#7a0026', '#f7f4ef'],
  Vega: ['#1d3c34', '#a4d65e'],
  'Muscle Milk': ['#111', '#d7c797'],
  'Naked Nutrition': ['#f3f1ec', '#1c1c1c'],
  BulkSupplements: ['#e8e4da', '#3a3a3a'],
  'Body Fortress': ['#8a0f0f', '#ffd200'],
};

/* --- Search suggestions & trending --- */
const SUGGESTIONS = [
  'protein powder', 'protein powder chocolate', 'protein powder vanilla',
  'whey protein isolate', 'plant based protein powder', 'protein powder sugar free',
  'creatine monohydrate', 'pre workout', 'protein shaker bottle', 'protein bars',
];

const RUFUS_SUMMARY = {
  results: 'For everyday muscle building, whey blends like Optimum Nutrition offer the best value per serving. If you want the cleanest label, Levels and Ascent skip artificial sweeteners. Going dairy-free? Orgain is the top-rated plant pick.',
  chips: ['Best for muscle gain?', 'Cleanest ingredients?', 'Best value per serving?', 'Dairy-free options?'],
  answers: {
    'Best for muscle gain?': 'For muscle gain, prioritize protein per scoop and leucine: Ascent (25g, isolate) digests fastest post-workout, while Gold Standard (24g) is the proven value pick — 240K+ reviewers agree.',
    'Cleanest ingredients?': 'Levels has just 5 ingredients with no artificial sweeteners, and Ascent uses only stevia. Both are grass-fed or native whey. Jocko Mölk adds probiotics with monk fruit sweetening.',
    'Best value per serving?': 'Optimum Nutrition Gold Standard works out to about $1.34 per serving — the lowest among top-rated wheys here. Subscribe & Save takes another 10% off.',
    'Dairy-free options?': 'Orgain Organic is the standout: 21g plant protein, USDA organic, and 94K+ ratings at the lowest price in this list. It\'s also the Overall Pick for vegan protein.',
  },
};

/* --- Seeded account data --- */
const ACCOUNT = {
  name: 'Takao',
  city: 'San Francisco',
  zip: '94107',
  address: '2261 Market St, San Francisco, CA 94114',
  payment: 'Visa ending in 4242',
  prime: true,
};

const SEED_ORDERS = [
  {
    id: '112-4297631-8804241',
    date: 'June 14, 2026',
    status: 'Delivered June 16',
    items: [{ productId: 'optimum', qty: 1, price: 38.99, sns: true }],
  },
  {
    id: '112-9921407-1130667',
    date: 'May 12, 2026',
    status: 'Delivered May 14',
    items: [{ productId: 'orgain', qty: 2, price: 29.59, sns: false }],
  },
];

/* Merge harvested/extracted data baked in at build time (see data/) */
window.AMZ_DATA = { CATALOG, CDN, BRAND_COLORS, SUGGESTIONS, RUFUS_SUMMARY, ACCOUNT, SEED_ORDERS };
