// A category page: one section of the work, every item in it, nothing else.
//
// Against `/` and `/lens/<slug>`, which argue a case by selecting evidence, a
// category page is the index — it shows everything in that section, in a fixed
// order, at one size. That difference is the whole reason both exist
// (docs/adaptive-portfolio-architecture.md §14.1), so the page is deliberately
// plain: a title, one line, and the cards.
import { esc, t, tb, plain, href, mediaFill } from "./html.mjs";
import { head, nav, langSwitch, footer, scripts } from "./shell.mjs";
import { inputLabel, status } from "./sections.mjs";

const CTA = {
  live: { en: "Try it ↗", jp: "触ってみる ↗" },
  caseStudy: { en: "Case study →", jp: "ケーススタディ →" },
  repo: { en: "Source ↗", jp: "ソース ↗" },
  external: { en: "Open ↗", jp: "開く ↗" },
};

/** The one destination a card opens, and the words on it. */
function destination(item) {
  const l = item.links ?? {};
  if (item.playable && l.live) return { url: l.live, label: CTA.live, external: true };
  if (l.caseStudy) return { url: l.caseStudy, label: CTA.caseStudy, external: false };
  if (l.live) return { url: l.live, label: CTA.external, external: true };
  if (l.external) return { url: l.external, label: CTA.external, external: true };
  if (l.repo) return { url: l.repo, label: CTA.repo, external: true };
  return null;
}

/** The card heading: the name people use, not the full title of the work. */
const cardName = (item) => {
  const name = item.shortTitle ?? item.title;
  return item.jpTitle && item.jpTitle !== name
    ? t({ en: name, jp: item.jpTitle })
    : esc(name);
};

function card(item, ctx) {
  const to = destination(item);
  const url = to ? (to.external ? to.url : href(ctx, to.url)) : null;
  const open = to ? ` tabindex="0" data-href="${esc(url)}"${to.external ? ' data-external="true"' : ""}` : "";
  const link = to
    ? `<a class="cat-card-cta" href="${esc(url)}"${to.external ? ' target="_blank" rel="noopener"' : ""}>${t(to.label)}</a>`
    : "";
  const chips = [
    item.input ? `<span class="pill pill--in">${inputLabel(item.input)}</span>` : "",
    status(item.status),
  ].filter(Boolean).join("");
  const meta = item.cardKind;
  return `        <article class="cat-card"${open}>
          <div class="cat-card-media">${mediaFill(item, ctx)}</div>
          <div class="cat-card-body">
            ${chips ? `<p class="chips">${chips}</p>` : ""}
            <h3 class="cat-card-title">${cardName(item)}</h3>
            ${meta ? `<p class="cat-card-kind">${t(meta)}</p>` : ""}
            <p class="cat-card-desc">${tb(item.cardLine ?? item.summary)}</p>
            ${link}
          </div>
        </article>`;
}

function group(g, lib, ctx, index, total) {
  const items = g.items.map((id) => lib.evidence.get(id)).filter(Boolean);
  const heading = g.title
    ? `      <div class="cat-group-head">
        <h2 class="cat-group-title">${t(g.title)}</h2>
        ${g.note ? `<p class="cat-group-note">${t(g.note)}</p>` : ""}
      </div>`
    : "";
  return `    <section class="cat-group"${g.title ? ` aria-label="${esc(plain(g.title))}"` : ""}>
${heading}
      <div class="cat-grid">
${items.map((item) => card(item, ctx)).join("\n")}
      </div>
    </section>`;
}

export function renderCategory({ category, lib, css, ctx }) {
  const count = category.groups.reduce((n, g) => n + g.items.length, 0);
  const first = lib.evidence.get(category.groups[0].items[0]);
  const pageCtx = { ...ctx, ogImage: ctx.ogImage ?? first?.assets?.hero ?? first?.assets?.thumb };
  const seo = { seo: { ...category.seo, noindex: false } };

  return `<!DOCTYPE html>
<!-- GENERATED by src/build.mjs from src/categories/${category.slug}.json — edit the data or the category, then run: node src/build.mjs -->
<html lang="en" data-category="${category.slug}">
${head({ lens: seo, ctx: pageCtx, css })}
<body>
${nav(pageCtx, category.output)}
  <main class="cat-page">
    <header class="cat-head">
      <h1 class="cat-title">${t(category.title)}</h1>
      <p class="cat-lede">${tb(category.lede)}</p>
      <p class="cat-count">${count}<span class="t-en"> projects</span><span class="t-jp"> 件</span></p>
    </header>

${category.groups.map((g, i) => group(g, lib, pageCtx, i, category.groups.length)).join("\n\n")}
  </main>

${langSwitch()}

${footer({ lib, ctx: pageCtx })}

${scripts()}
</body>
</html>
`;
}
