// Assembles one Lens into a full HTML document.
// section.type → component. Adding a section type = adding one function here.
import { head, nav, langSwitch, footer, scripts } from "./shell.mjs";
import { hero } from "./hero.mjs";
import { proofSection } from "./proof.mjs";
import {
  exploringSection, experimentsSection, venturesSection, toolsSection,
  careerArcSection, capabilitiesSection, studioSection, contactSection,
} from "./sections.mjs";
import { lensEvidenceIds } from "../validate.mjs";

const SECTIONS = {
  proof: proofSection,
  exploring: exploringSection,
  experiments: experimentsSection,
  ventures: venturesSection,
  tools: toolsSection,
  "career-arc": careerArcSection,
  capabilities: capabilitiesSection,
  studio: studioSection,
};

export function renderLens({ lens, lib, css, ctx }) {
  const usedEvidence = [...new Set(lensEvidenceIds(lens))].map((id) => lib.evidence.get(id)).filter(Boolean);
  const showLensNote = lens.lensNote ?? lens.slug !== "default";
  const firstProof = lens.sections.find((s) => s.type === "proof")?.items?.[0];
  const firstItem = firstProof ? lib.evidence.get(firstProof.id) : null;
  const pageCtx = { ...ctx, ogImage: ctx.ogImage ?? firstItem?.assets?.hero ?? firstItem?.assets?.thumb };

  const body = lens.sections.map((section) => {
    if (section.type === "contact") return contactSection({ section, lens, lib, ctx: pageCtx, showLensNote });
    return SECTIONS[section.type]({ section, lens, lib, ctx: pageCtx, usedEvidence });
  });
  if (!lens.sections.some((s) => s.type === "contact")) body.push(contactSection({ lens, lib, ctx: pageCtx, showLensNote }));

  return `<!DOCTYPE html>
<!-- GENERATED by src/build.mjs from src/lenses/${lens.slug}.json — edit the data or the lens, then run: node src/build.mjs -->
<html lang="en" data-lens="${lens.slug}">
${head({ lens, ctx: pageCtx, css })}
<body>
${nav(pageCtx)}
${hero({ lens, lib, ctx: pageCtx })}
${body.join("\n\n")}

${langSwitch()}

${footer({ lib, ctx: pageCtx })}

${scripts()}
</body>
</html>
`;
}
