export const CATEGORY_ORDER = Object.freeze([
  'Interactive Experience',
  'AI Products',
  'AI Tools',
  'Product Design',
  'Brand Experience',
]);

export const CATEGORY_LINKS = Object.freeze({
  'Interactive Experience': '../v3/interactive.html',
  'AI Products': '../v3/ai-products.html',
  'AI Tools': '../v3/ai-tools.html',
  'Product Design': '../v3/work.html',
  'Brand Experience': '../v3/brand.html',
});

const project = (entry) => Object.freeze(entry);

export const PROJECTS = Object.freeze([
  // ── 01. Interactive Experience ──
  project({
    slug: 'resona',
    title: 'Resona 響',
    tagline: 'Pseudo-haptic sensory physics for flat glass',
    category: 'Interactive Experience',
    year: 'Live · 2026',
    role: 'Motion Design & Engineering',
    client: 'Independent Research / Studio',
    tech: ['Web Animation API', 'Pseudo-Haptics', 'Canvas / Physics', 'Vite'],
    summary: 'Pseudo-haptics: animation that makes you feel mass, resistance, and friction through a screen that has neither.',
    href: 'https://resona-motion.vercel.app',
    image: null,
    imageAlt: 'Resona interactive motion simulation',
    art: 'resona',
    meta: 'Web animation · Pseudo-haptics · Pure CSS & Canvas',
    featured: true,
    featuredNumber: '01',
    gridSpan: 'two-col',
  }),
  project({
    slug: 'rakugaki-jam',
    title: 'Rakugaki Jam',
    tagline: 'Multi-device realtime collaborative canvas',
    category: 'Interactive Experience',
    year: 'Live · 2026',
    role: 'Creative Technologist & Lead Architect',
    client: 'Independent Experience',
    tech: ['Snap Pair', 'Firebase RTDB', 'Canvas 2D', 'WebSockets'],
    summary: 'Doodle on your phone, fling it onto the shared wall. A crowd-drawn VJ jam that needs no app install.',
    href: 'https://rakugaki-jam.vercel.app',
    image: null,
    imageAlt: 'Rakugaki Jam shared wall interface',
    art: 'rakugaki',
    meta: 'Snap Pair · Firebase RTDB · Multi-touchpoint',
    featured: true,
    featuredNumber: '02',
    gridSpan: 'two-col',
  }),
  project({
    slug: 'kao-game',
    title: 'Kao Game 顔ゲーム',
    tagline: 'Your face is the game controller',
    category: 'Interactive Experience',
    year: 'In Progress · 2026',
    role: 'Interaction Designer & Vision Engineer',
    client: 'Independent Experience',
    tech: ['Face Tracking', 'Vision ML', 'Web Audio', 'Canvas'],
    summary: 'A game you play with your face. Pull the expressions the game asks for — facial muscle exercise made genuinely fun to repeat.',
    href: '../v3/interactive.html#experiences',
    image: null,
    imageAlt: 'Kao Game facial tracking interface',
    art: 'kao',
    meta: 'Face tracking · Vision ML · Interactive game',
    featured: true,
    featuredNumber: '03',
    gridSpan: 'two-col',
  }),

  // ── 02. AI Products ──
  project({
    slug: 'verizon-ai-agents',
    title: 'Verizon AI Workflow',
    tagline: 'Enterprise multi-agent UX system for 42 designers',
    category: 'AI Products',
    year: '2025–Present',
    role: 'Lead Product Designer · Agentic UX & AI Systems',
    client: 'Verizon Design Systems Org',
    tech: ['Multi-Agent Architecture', 'Figma API', 'Design Tokens', 'LLM Workflows'],
    summary: 'A fleet of ten purpose-built AI agents woven into the existing workflow of a 42-designer, six-brand organization.',
    href: '../v3/projects/verizon-ai-agents.html',
    image: 'assets/thumbs/verizon-ai-agents.jpg',
    imageAlt: 'Verizon AI Agent system dashboard',
    art: null,
    meta: 'UX strategy · AI architecture · System integration',
    featured: true,
    featuredNumber: '04',
    gridSpan: 'two-col',
  }),
  project({
    slug: 'moime-app',
    title: 'Moime.app',
    tagline: 'Multimodal AI link-in-bio reading physical flyers',
    category: 'AI Products',
    year: 'In Production · 2026',
    role: 'Founder & Full-Stack Product Architect',
    client: 'Moime Inc.',
    tech: ['React 19', 'Gemini Multimodal', 'Voice AI', 'Serverless'],
    summary: 'A link-in-bio platform for events and promo codes. Point it at a flyer and it extracts dates, discount codes, and venue metadata automatically.',
    href: '../v3/ai-products.html',
    image: null,
    imageAlt: 'Moime.app AI flyer scanning interface',
    art: 'moime',
    meta: 'Multimodal AI · React 19 · Gemini API',
    featured: true,
    featuredNumber: '05',
    gridSpan: 'two-col',
  }),
  project({
    slug: 'amazon-firetv',
    title: 'Amazon Shopping on Fire TV',
    tagline: 'Living room agentic commerce prototype',
    category: 'AI Products',
    year: '2026',
    role: 'Design & Engineering Lead',
    client: 'Amazon / Consumer Tech Concept',
    tech: ['Web Speech API', 'Firebase RTDB', '10-Foot UI', 'QR Pairing'],
    summary: 'A living prototype of agentic commerce for the living room: D-pad browsing, Alexa voice shopping, and one-scan phone pairing.',
    href: '../v3/projects/amazon-firetv.html',
    image: 'assets/thumbs/amazon-firetv.jpg',
    imageAlt: 'Amazon Fire TV shopping user experience',
    art: null,
    meta: 'HTML/CSS/JS · Firebase · Voice UX',
    featured: false,
    gridSpan: 'two-col',
  }),

  // ── 03. AI Tools & Skills ──
  project({
    slug: 'superforge',
    title: 'superforge',
    tagline: 'Autonomous multi-model software development suite',
    category: 'AI Tools',
    year: '2026–ongoing',
    role: 'Lead Developer & Architect',
    client: 'Open Source (MIT)',
    tech: ['Claude', 'Gemini', 'Codex', 'Shell / CLI', 'Prompt Systems'],
    summary: 'Fourteen specialist skills that route a build from one sentence through implementation, accessibility, and pre-launch checks.',
    href: '../v3/projects/superforge.html',
    image: 'assets/thumbs/superforge.jpg',
    imageAlt: 'Superforge agent orchestration architecture',
    art: null,
    meta: 'Claude · Codex · Gemini · Agent Teams',
    featured: false,
    gridSpan: 'three-col',
  }),
  project({
    slug: 'snap-pair',
    title: 'Snap Pair',
    tagline: 'Zero-config instant multi-device sync layer',
    category: 'AI Tools',
    year: 'Open Source',
    role: 'Library Author & Lead Maintainer',
    client: 'Open Source (MIT)',
    tech: ['React', 'Firebase RTDB', 'QR Auth', 'Zero-Config SDK'],
    summary: 'A pairing layer that lets every phone in the room join an interactive app in one scan. Powers Amazon, Rakugaki Jam, and Typespace.',
    href: '../v3/projects/snap-pair.html',
    image: 'assets/thumbs/snap-pair.jpg',
    imageAlt: 'Snap Pair QR code pairing interface',
    art: null,
    meta: 'Examples: Amazon · Rakugaki · Typespace',
    featured: false,
    gridSpan: 'three-col',
  }),
  project({
    slug: 'failforward',
    title: 'failforward',
    tagline: 'Failure memory and learning CLI for agents',
    category: 'AI Tools',
    year: 'Open Source',
    role: 'CLI & Workflow Architect',
    client: 'Open Source (MIT)',
    tech: ['Python', 'Codex', 'Gemini CLI', 'Local Memory'],
    summary: 'A zero-dependency CLI that records debugging failures and recalls lessons before similar work starts.',
    href: '../v3/projects/failforward.html',
    image: 'assets/thumbs/failforward.jpg',
    imageAlt: 'Failforward CLI terminal interface',
    art: null,
    meta: 'Python · Codex · Gemini · MIT',
    featured: false,
    gridSpan: 'three-col',
  }),

  // ── 04. Product Design ──
  project({
    slug: 'cli-studios',
    title: 'CLI Studios',
    tagline: 'Full mobile app overhaul and design system',
    category: 'Product Design',
    year: '2024',
    role: 'Lead Product Designer',
    client: 'CLI Studios Inc.',
    tech: ['Mobile iOS/Android', 'Design Tokens', 'Information Architecture'],
    summary: 'A mobile UX overhaul that began with information architecture and unified the mobile learning experience across platforms.',
    href: '../v3/projects/cli-studios.html',
    image: 'assets/thumbs/cli-studios.jpg',
    imageAlt: 'CLI Studios mobile dance learning app screens',
    art: null,
    meta: 'App design · Design system · Mobile UX',
    featured: false,
    gridSpan: 'three-col',
  }),
  project({
    slug: 'ela-quests',
    title: 'ELA Quests',
    tagline: 'Gamified digital learning curriculum for K-12',
    category: 'Product Design',
    year: '2023',
    role: 'Senior Product Designer',
    client: 'Amplify Education',
    tech: ['Curriculum UX', 'Gamification', 'Responsive Web', 'Design System'],
    summary: 'An engaging quest narrative interface transforming reading and writing lessons into interactive student adventures.',
    href: '../v3/work.html',
    image: 'assets/thumbs/ela-quests.jpg',
    imageAlt: 'ELA Quests digital learning interface',
    art: null,
    meta: 'EdTech · Quest interface · Gamified UX',
    featured: false,
    gridSpan: 'three-col',
  }),
  project({
    slug: 'verizon-totalwireless',
    title: 'Verizon Total Wireless',
    tagline: 'High-conversion e-commerce telecommunications flow',
    category: 'Product Design',
    year: '2024',
    role: 'UX Designer & Prototyper',
    client: 'Verizon Consumer Group',
    tech: ['Figma', 'Live HTML Prototyping', 'Design Systems', 'Checkout UX'],
    summary: 'A shopping-flow redesign that made pricing tiers, device compatibility, and plan customization effortless to navigate.',
    href: '../v3/projects/verizon-totalwireless.html',
    image: 'assets/thumbs/verizon-totalwireless.jpg',
    imageAlt: 'Verizon Total Wireless checkout interface',
    art: null,
    meta: 'Telecom · E-commerce UX · Live prototyping',
    featured: false,
    gridSpan: 'three-col',
  }),

  // ── 05. Brand Experience ──
  project({
    slug: 'coca-cola',
    title: 'Coca-Cola',
    tagline: 'Global visual campaign and brand design worlds',
    category: 'Brand Experience',
    year: 'Global Markets',
    role: 'Senior Designer · Ogilvy BIG',
    client: 'The Coca-Cola Company (Ogilvy)',
    tech: ['Brand Systems', 'Global Key Visuals', 'Campaign Guidelines', 'OOH'],
    summary: 'Two global visual campaign worlds designed to flex across diverse international markets, formats, and cultural contexts.',
    href: '../v3/projects/coca-cola.html',
    image: 'assets/thumbs/coca-cola.jpg',
    imageAlt: 'Coca-Cola global brand campaign visuals',
    art: null,
    meta: 'Campaign · Visual direction · Brand system',
    featured: false,
    gridSpan: 'three-col',
  }),
  project({
    slug: 'odell-education',
    title: 'Odell Education',
    tagline: 'National literacy curriculum publishing system & brand',
    category: 'Brand Experience',
    year: '2023',
    role: 'Brand Designer & Art Director',
    client: 'Odell Education Inc.',
    tech: ['Brand Identity', 'Editorial System', 'Print & Digital', 'Typography'],
    summary: 'A comprehensive visual identity, typographic design system, and multi-state curriculum brand platform.',
    href: '../v3/projects/odell-education.html',
    image: 'assets/thumbs/odell-education.jpg',
    imageAlt: 'Odell Education branding and curriculum design',
    art: null,
    meta: 'Brand identity · Editorial design · Systems',
    featured: false,
    gridSpan: 'three-col',
  }),
  project({
    slug: 'kitadoko',
    title: 'Kitadoko',
    tagline: '150-year-old barbershop full rebrand & space design',
    category: 'Brand Experience',
    year: '2023',
    role: 'Creative Director & Space Designer',
    client: 'Kitadoko Hair Salon',
    tech: ['CX Architecture', 'Space Design', 'Brand Identity', 'Service Design'],
    summary: 'Full CX and space redesign of a 150-year-old Tokyo barbershop into personal hair styling, taking repeat rate from 0% to 90%.',
    href: '../v3/projects/kitadoko.html',
    image: 'assets/thumbs/kitadoko.jpg',
    imageAlt: 'Kitadoko salon interior and brand signage',
    art: null,
    meta: '150-year rebrand · Space design · CX strategy',
    featured: false,
    gridSpan: 'three-col',
  }),
]);

const PROJECTS_BY_SLUG = new Map(PROJECTS.map((entry) => [entry.slug, entry]));

export function projectBySlug(slug) {
  return PROJECTS_BY_SLUG.get(slug) ?? null;
}

