export const CATEGORY_ORDER = Object.freeze([
  'Interactive Experience',
  'AI Products',
  'AI Tools',
  'Product Design',
  'Brand Experience',
]);

const project = (entry) => Object.freeze(entry);

export const PROJECTS = Object.freeze([
  project({
    slug: 'resona',
    title: 'Resona 響',
    category: 'Interactive Experience',
    year: 'Live',
    role: 'Motion design',
    summary: 'Pseudo-haptics: animation that makes you feel mass and friction through a screen that has neither.',
    href: 'https://resona-motion.vercel.app',
    image: null,
    imageAlt: '',
    art: 'resona',
    meta: 'Web animation · Pseudo-haptics',
  }),
  project({
    slug: 'rakugaki-jam',
    title: 'Rakugaki Jam',
    category: 'Interactive Experience',
    year: 'Live',
    role: 'Interactive experience',
    summary: 'Doodle on your phone, fling it onto the shared wall. A crowd-drawn VJ jam that needs no app install.',
    href: 'https://rakugaki-jam.vercel.app',
    image: null,
    imageAlt: '',
    art: 'rakugaki',
    meta: 'Snap Pair · Firebase RTDB',
  }),
  project({
    slug: 'marubatsu',
    title: 'Marubatsu 2.0',
    category: 'Interactive Experience',
    year: 'Shipped',
    role: 'Independent product',
    summary: 'A real-time 4×4 tic-tac-toe game with pass-and-play, online pairing, and a Gemini-powered opponent.',
    href: '../v3/projects/marubatsu.html',
    image: 'assets/thumbs/marubatsu.jpg',
    imageAlt: '',
    art: null,
    meta: 'Next.js 16 · Firebase · Gemini',
  }),
  project({
    slug: 'verizon-ai-agents',
    title: 'Verizon AI Workflow',
    category: 'AI Products',
    year: '2025–Present',
    role: 'Lead Product Designer · Agentic UX & AI Systems',
    summary: 'A fleet of ten purpose-built AI agents woven into the existing workflow of a 42-designer, six-brand organization.',
    href: '../v3/projects/verizon-ai-agents.html',
    image: 'assets/thumbs/verizon-ai-agents.jpg',
    imageAlt: '',
    art: null,
    meta: 'UX strategy · AI architecture · System integration',
  }),
  project({
    slug: 'amazon-firetv',
    title: 'Amazon Shopping on Fire TV',
    category: 'AI Products',
    year: '2026',
    role: 'Design & Engineering',
    summary: 'A living prototype of agentic commerce for the living room: D-pad browsing, Alexa voice shopping, and one-scan phone pairing.',
    href: '../v3/projects/amazon-firetv.html',
    image: 'assets/thumbs/amazon-firetv.jpg',
    imageAlt: '',
    art: null,
    meta: 'HTML/CSS/JS · Firebase · Web Speech API',
  }),
  project({
    slug: 'superforge',
    title: 'superforge',
    category: 'AI Tools',
    year: '2026–ongoing',
    role: 'Lead developer & prompt systems architect',
    summary: 'Fourteen specialist skills that route a build from one sentence through implementation, accessibility, and pre-launch checks.',
    href: '../v3/projects/superforge.html',
    image: 'assets/thumbs/superforge.jpg',
    imageAlt: '',
    art: null,
    meta: 'Claude · Codex · Gemini · Kimi · MIT',
  }),
  project({
    slug: 'snap-pair',
    title: 'Snap Pair',
    category: 'AI Tools',
    year: 'Open source',
    role: 'Realtime library & Claude skill',
    summary: 'A React and Firebase pairing layer that lets every phone in the room join an app in one scan.',
    href: '../v3/projects/snap-pair.html',
    image: 'assets/thumbs/snap-pair.jpg',
    imageAlt: '',
    art: null,
    meta: 'React + Firebase · MIT',
  }),
  project({
    slug: 'failforward',
    title: 'failforward',
    category: 'AI Tools',
    year: 'Open source',
    role: 'CLI & agent workflow',
    summary: 'A zero-dependency CLI that records failures and recalls the useful lessons before similar work starts.',
    href: '../v3/projects/failforward.html',
    image: 'assets/thumbs/failforward.jpg',
    imageAlt: '',
    art: null,
    meta: 'Python · Codex · Gemini · MIT',
  }),
  project({
    slug: 'verizon-totalwireless',
    title: 'Verizon Total Wireless',
    category: 'Product Design',
    year: '2024',
    role: 'UX Designer & Prototyper',
    summary: 'A shopping-flow redesign that made pricing, compatibility, and e-commerce decisions easier to understand.',
    href: '../v3/projects/verizon-totalwireless.html',
    image: 'assets/thumbs/verizon-totalwireless.jpg',
    imageAlt: '',
    art: null,
    meta: 'Telecom · E-commerce UX · Live prototyping',
  }),
  project({
    slug: 'cli-studios',
    title: 'CLI Studios',
    category: 'Product Design',
    year: '2024',
    role: 'Lead Product Designer',
    summary: 'A mobile UX overhaul that began with information architecture and became a unified design system.',
    href: '../v3/projects/cli-studios.html',
    image: 'assets/thumbs/cli-studios.jpg',
    imageAlt: '',
    art: null,
    meta: 'App design · Design system · Mobile UX',
  }),
  project({
    slug: 'tmobile',
    title: 'T-Mobile BOPIS',
    category: 'Product Design',
    year: '2024',
    role: 'Lead UX',
    summary: 'An integrated buy-online, pick-up-in-store experience spanning customer app, kiosk, staff tools, and voice.',
    href: '../v3/projects/tmobile.html',
    image: 'assets/thumbs/tmobile.jpg',
    imageAlt: '',
    art: null,
    meta: 'Retail innovation · Service design · Multi-touchpoint',
  }),
  project({
    slug: 'coca-cola',
    title: 'Coca-Cola',
    category: 'Brand Experience',
    year: 'Global markets',
    role: 'Senior Designer · Ogilvy Brand Integration Group',
    summary: 'Two global visual campaign worlds designed to flex across markets, formats, and cultural contexts.',
    href: '../v3/projects/coca-cola.html',
    image: 'assets/thumbs/coca-cola.jpg',
    imageAlt: '',
    art: null,
    meta: 'Campaign · Visual direction · Brand system',
  }),
  project({
    slug: 'value-frontier',
    title: 'Value Frontier',
    category: 'Brand Experience',
    year: '2019',
    role: 'Brand Strategist & Creative Director',
    summary: 'A strategic rebrand from sustainability consultancy to a premium, multi-industry identity system.',
    href: '../v3/projects/value-frontier.html',
    image: 'assets/thumbs/value-frontier.jpg',
    imageAlt: '',
    art: null,
    meta: 'Brand strategy · Identity system',
  }),
  project({
    slug: 'festival-design',
    title: 'Akimatsuri Festival Design',
    category: 'Brand Experience',
    year: '2022–2024',
    role: 'Festival Chairperson & Creative Director',
    summary: 'Original games, branding, and volunteer systems designed as one coherent Japanese school-festival experience.',
    href: '../v3/projects/festival-design.html',
    image: 'assets/thumbs/festival-design.jpg',
    imageAlt: '',
    art: null,
    meta: 'Experience · Identity · Operations',
  }),
]);

const PROJECTS_BY_SLUG = new Map(PROJECTS.map((entry) => [entry.slug, entry]));

export function projectBySlug(slug) {
  return PROJECTS_BY_SLUG.get(slug) ?? null;
}
