// /api/admin/jev/suggest — "say what you want → 3 candidate configs → Jev sorts them".
//
//   POST { request?, config? } → { ok, request, candidates: [{ name, config, why, readings? }], judged, error? }
//
// Owner only, like /api/admin/jev/motion: src/middleware.ts has already
// refused anyone but an allowed admin, and requireAdmin checks again. Same-
// origin only. The three are generated by rules (no key needed); Jev only
// sorts them, and without its key they come back unsorted (judged: false).
// The work is in src/server/motion-suggest.mjs; see docs/jev.md.
import type { APIRoute } from "astro";
import { handleSuggest } from "../../../../server/motion-suggest.mjs";
import { json, requireAdmin, sameOrigin } from "../_auth";

export const prerender = false;

export const POST: APIRoute = async (context) => {
  const denied = requireAdmin(context);
  if (denied) return denied;
  if (!sameOrigin(context.request, context.url)) return json({ ok: false, error: "cross-origin", message: "Requests must come from this site." }, 403);
  return handleSuggest(context.request);
};

export const ALL: APIRoute = () => json({ ok: false, error: "method-not-allowed" }, 405, { allow: "POST" });
